Update profile-3d.yml

diff --git a/.github/workflows/profile-3d.yml b/.github/workflows/profile-3d.yml
--- a/.github/workflows/profile-3d.yml
+++ b/.github/workflows/profile-3d.yml
@@ -24,14 +24,19 @@ jobs:
       - name: Set Git remote manually
         run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
 
-      - name: Pull latest changes
+      - name: Configure Git user
+        run: |
+          git config user.name "GitHub Action"
+          git config user.email "action@github.com"
+
+      - name: Pull latest changes with rebase
+        continue-on-error: true
         run: git pull origin ${GITHUB_REF##*/} --rebase
 
       - name: Commit & Push
         run: |
-          git config user.name "GitHub Action"
-          git config user.email "action@github.com"
           git add profile-3d-contrib/
           git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
-          git push origin ${GITHUB_REF##*/}
+          git push origin ${GITHUB_REF##*/} || echo "Push failed, likely no rebase"
+
 
